
spring:
  application:
    name: shopapp

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/shopweb}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:Anhthucdz123@}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jwt:
    expiryMinute: ${EXPIRY_MINUTE:60}
    expiryHour: ${EXPIRY_HOUR:5}
    expiryDay: 14
    accessKey: ${ACCESS_KEY:c2VjcmV0QGtleS5hcGlfaGFzX2JlZW5fZGVzaWduZWRfYnlfVGF5TFE=}
    refreshKey: ${REFRESH_KEY:9k1jJAWAKQCnCEz1pwcPNegbHoLugf9hgEnn6sz5pFc=}
  jpa:
    hibernate:
      ddl-auto: update  # Các giá trị có thể là none, create, update, create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        enable_lazy_load_no_trans: true
        format_sql: true
    show-sql: true
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  kafka:
    bootstrap-servers: localhost:9092

  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    username: ${MAIL_USERNAME:ckp2004vn@gmail.com}
    password: ${MAIL_PASSWORD:kltqohttmkznubrc}
    port: ${MAIL_PORT:587}
    properties:
      smtp:
        auth: true
      mail:
        smtp:
          starttls:
            enable: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 15MB
      max-request-size: 20MB
  web:
    resources:
      static-locations: file:///C:/Users/T/Desktop/images/
app:
  cors:
    allowed-origin: ${API_CROSS:http://localhost:3000}
payment:
  vnpay:
    vnp_PayUrl: ${PAY_URL:https://sandbox.vnpayment.vn/paymentv2/vpcpay.html}
    vnp_TmnCode: ${TMN_CODE:58X4B4HP}
    secretKey: ${SECRET_KEY:VRLDWNVWDNPCOEPBZUTWSEDQAGXJCNGZ}
    vnp_ReturnUrl: ${RETURN_URL:http://localhost:8080/payment/vn-pay-callback}
    vnp_Version: ${VERSION:2.1.0}
    vnp_Command: ${COMMAND:pay}
    orderType: ${ORDER_TYPE:other}
debug: true

